CREATE TABLE IF NOT EXISTS community_users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    location GEOGRAPHY(Point),
    radius DECIMAL(38, 2)
);