DROP TYPE IF EXISTS post_type;
CREATE TYPE post_type AS ENUM (
    'offer',
    'request'
);

DROP TYPE IF EXISTS help_items;
CREATE TYPE help_items AS SET (
    'Picking up supplies',
    'Running errands',
    'Phone call',
    'Online chat',
    'Dog walking',
    'Other'
);

DROP TYPE IF EXISTS urgency;
CREATE TYPE urgency AS ENUM (
    'low',
    'medium',
    'high'
);

CREATE TABLE IF NOT EXISTS community_posts (
    post_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES community_users(user_id),
    post_type post_type NOT NULL,
    help_items help_items NOT NULL,
    description TEXT NOT NULL,
    urgency urgency,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
);