CREATE TABLE IF NOT EXISTS community_categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL
);

INSERT INTO community_categories (category) 
VALUES 
    ('Picking up supplies'),
    ('Running errands'),
    ('Phone call'),
    ('Online chat'),
    ('Dog walking'),
    ('Other');